### ISSUE TITLE
no module named 'scapy.modules.six.moves'

### ISSUE THREAD

**Issue by simbadmorehod** [nxenon/h2spacex#2]
Windows `no module named 'scapy.modules.six.moves'` = )

**Comment by nxenon** [comment]
Could you describe more? I don't get your problem!

**Comment by simbadmorehod** [comment]
One of my friends is trying to run this on Windows

**Comment by nxenon** [comment]
This is not a good sample for error. Also you need to attach the code you are running and the full error message.

**Comment by simbadmorehod** [comment]
Yes, I understand, but so far he just has a screenshot of the problem, I'm remotely trying to figure out maybe he's using the wrong version of python, I'm sorry, I'll write or close the ticket later as solved, the problem occurs when importing the library

**Comment by simbadmorehod** [comment]
```
Traceback (most recent call last):
  File "C:\Users\HOME\Documents\get_bobble_heads_h2spacex.py", line 2, in <module>
    from h2spacex import h2_frames
  File "C:\Users\HOME\crypto\Lib\site-packages\h2spacex\__init__.py", line 1, in <module>
    from .h2_connection import H2Connection
  File "C:\Users\HOME\crypto\Lib\site-packages\h2spacex\h2_connection.py", line 6, in <module>
    import scapy.contrib.http2 as h2
  File "C:\Users\HOME\crypto\Lib\site-packages\scapy\contrib\http2.py", line 50, in <module>
    import scapy.fields as fields
  File "C:\Users\HOME\crypto\Lib\site-packages\scapy\fields.py", line 24, in <module>
    from scapy.config import conf
  File "C:\Users\HOME\crypto\Lib\site-packages\scapy\config.py", line 19, in <module>
    from scapy import VERSION, base_classes
  File "C:\Users\HOME\crypto\Lib\site-packages\scapy\base_classes.py", line 26, in <module>
    from scapy.modules.six.moves import range
ModuleNotFoundError: No module named 'scapy.modules.six.moves'
```

The library is installed at the same time

**Comment by nxenon** [comment]
Can you create a new virtual environment and install it again with the instructions in the REAADME. And what is your python version?

**Comment by simbadmorehod** [comment]
3.12

**Comment by simbadmorehod** [comment]
Yes, we have created a new virtual environment

**Comment by nxenon** [comment]
I tested on windows with python 3.11.4 and it was completely OK. I think you have not followed the installation instructions or there is something with your python version.

Installation:
```bash
python -m venv  venv
.\venv\Scripts\activate.ps1
pip install h2spacex
python test1-example.py
```

**Comment by simbadmorehod** [comment]
Unchanged, if running on python 3.10 works fine, I think this is a feature of 3.12, maybe we broke it, you can close the ticket
